"""Managed beets integration: config generation and import runs.

The vendored beets (see fetchdeps.PIP_PACKAGES) is configured so a plain
``beet import`` reproduces the user's MusicBrainz Picard setup:

* paths use the ``mlo_dir`` album template field computed by the bundled
  ``mloplugin`` from MLO's actual naming script (server/naming.py), so
  beets organizes files into the identical folder structure;
* the plugin adds locale translations (MusicBrainz aliases), work /
  movement tags from work relationships, and release-type
  capitalization (EP uppercased, others Title Case);
* imports run headless: ``quiet`` mode auto-applies strong MusicBrainz
  matches and falls back to "as-is" for weak ones.
"""
import os
import subprocess
import sys
import threading

from mlo.config import load_config
from mlo.fetchdeps import pip_package_path
from mlo.tools import python_pkg_path

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PLUGIN_DIR = os.path.join(REPO_ROOT, "server", "beets")


def data_dir():
    """All app state lives in <music folder>/.mlo/data (see mlo.paths)."""
    from mlo.paths import app_data_dir
    return app_data_dir()


def db_path():
    return os.path.join(data_dir(), "beets-library.db")


def _library_dir(cfg):
    """The library folder beets organizes into: <music folder>/Artists."""
    from mlo.paths import library_root
    mf = str(cfg.get("music_folder") or "")
    return library_root(mf) if mf else ""


def config_path():
    """beets-config.yaml; rewritten in place when it still names a stale
    library path.

    The config embeds ABSOLUTE ``library:`` and ``directory:`` paths, so a
    moved music folder (the whole layout travelling with it) — or a config
    generated before the library moved into ``Artists/`` — would leave a
    file pointing at the beets DB / target folder of the old location;
    beets would then create a second, empty library there. Regenerate
    whenever either recorded path differs."""
    path = os.path.join(data_dir(), "beets-config.yaml")
    try:
        with open(path, encoding="utf-8") as f:
            current = f.read()
    except OSError:
        return path
    cfg = load_config()
    wanted = {"library:": _yq(db_path()), "directory:": _yq(_library_dir(cfg))}
    lines = current.splitlines()
    if any(not any(line.startswith(key) and want in line for line in lines)
           for key, want in wanted.items()):
        try:
            _write_config(generate_config(cfg))
        except OSError:
            pass  # unreadable/absent config: the next write fixes it
    return path


def _yq(text):
    """Quote a string for YAML with forward slashes (Windows-safe)."""
    return '"' + str(text).replace("\\", "/").replace('"', "'") + '"'


def generate_config(cfg=None):
    """Render beets config.yaml from MLO config; returns the YAML text."""
    cfg = cfg or load_config()
    locale = str(cfg.get("beets_locale") or "en").strip()
    lines = [
        "# Generated by la musica — edits are overwritten.",
        f"directory: {_yq(_library_dir(cfg))}",
        f"library: {_yq(db_path())}",
        "",
        "import:",
        "  copy: no",
        "  move: yes",
        "  write: yes",
        "  quiet: yes",
        "  quiet_fallback: asis",
        "  duplicate_action: skip",
        f"  languages: {_yq(locale)}",
        "",
        "paths:",
        # %func{...} is beets template-function call syntax: %mlo_dir
        # computes the album folder from MLO's naming script and $mlo_file
        # (a plugin item field) supplies the "D-TT Title" filename.
        "  default: %mlo_dir{$mlo_file}",
        "",
        "plugins: [mloplugin]",
        f"pluginpath: [{_yq(PLUGIN_DIR)}]",
        "",
        "mloplugin:",
        f"    locale: {_yq(locale)}",
        f"    translations: {'yes' if cfg.get('beets_translations', True) else 'no'}",
        f"    work_movement: {'yes' if cfg.get('beets_work_movement', True) else 'no'}",
        f"    release_type_caps: {'yes' if cfg.get('beets_release_type_caps', True) else 'no'}",
        f"    credits: {'yes' if cfg.get('beets_credits', True) else 'no'}",
        "",
        "musicbrainz:",
        "  enabled: yes",
        # Genres are NEVER beets' to write. The app has its own source-ordered
        # genre chain (genre_sources) that FILLS a track's GENRE and never
        # replaces one — the wizard's genre step, script 8 and the import
        # stamp all go through it. beets fetches genres from MusicBrainz on
        # every import and writes them back with import.write, so leaving this
        # on silently overwrote genres the user had just entered in the
        # wizard. Off: beets keeps the file's own GENRE (it reads existing
        # tags into the item), and the chain remains the single writer.
        "  genres: no",
        "",
        # Tag writes come from the plugin's own logic through MLO's tag
        # layer, so beets' own asis/autotag writes stay Picard-compatible.
        "match:",
        "  ignored_media: ['Data CD', 'DVD', 'DVD-Video', 'Music DVD',",
        "                  'VCD', 'SVCD', 'UMD', 'VHS']",
    ]
    text = "\n".join(lines) + "\n"
    return text


def _write_config(text):
    """Atomically write the generated YAML; returns its path."""
    os.makedirs(data_dir(), exist_ok=True)
    path = os.path.join(data_dir(), "beets-config.yaml")
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    os.replace(tmp, path)
    return path


def write_config(cfg=None):
    return _write_config(generate_config(cfg))


def beets_available():
    """(version_label, plugin_dir) when vendored beets is installed."""
    if not pip_package_path("beets"):
        return None
    from mlo.fetchdeps import PINNED, installed_versions
    # The version of the folder that is actually on sys.path. The pin was
    # reported for any folder that existed, so an updated beets kept telling
    # the Beets page it was still 2.4.0; the pin stays the fallback for a
    # folder neither pip's metadata nor its name can date.
    return installed_versions().get("beets") or PINNED["beets"]["version"]


def _python():
    """A real interpreter for the beets subprocess; sys.executable points at
    the frozen server exe in PyInstaller builds."""
    if not getattr(sys, "frozen", False):
        return sys.executable
    import shutil
    for cand in ("python", "python3", "py"):
        found = shutil.which(cand)
        if found:
            return found
    return sys.executable


def _env():
    """Env for the beets subprocess: repo root + vendored beets on sys.path."""
    pkg = python_pkg_path("beets")
    env = dict(os.environ)
    parts = [REPO_ROOT]
    if pkg:
        parts.insert(0, pkg)
    env["PYTHONPATH"] = os.pathsep.join(parts) + os.pathsep + env.get("PYTHONPATH", "")
    env["PYTHONIOENCODING"] = "utf-8"
    return env


def run_beets_import(paths, cfg=None, timeout=7200, on_line=None):
    """Run `beet import` over the given folders headlessly.

    Returns (ok, output). The generated config is rewritten first so the
    current naming script / plugin settings always apply.

    The child's output is STREAMED, not buffered: beets is the longest step
    of a Run All, and a run that prints nothing for half an hour is
    indistinguishable from a hung one (the UI bar only moves on a tick, and
    `capture_output` withheld every line until the process exited). Each line
    goes to *on_line* for progress, and the tail is still returned for the
    error message. stdin is /dev/null so a prompt can never block the import
    for the whole timeout — the config's own `import.quiet` is what answers
    beets' decisions (the `--quiet` FLAG only suppresses this output).
    """
    if not paths:
        return False, "no paths given"
    if not beets_available():
        return False, "beets is not installed — install it from Settings → Beets"
    cfg = cfg or load_config()
    conf = write_config(cfg)
    cmd = [
        _python(), "-u", "-m", "beets",
        "--config", conf,
        "import", "--group-albums",
        *paths,
    ]
    tail: list[str] = []

    def _reader(stream):
        try:
            for raw in stream:
                line = raw.rstrip("\r\n")
                tail.append(line)
                del tail[:-80]           # only the tail is ever reported
                if on_line:
                    try:
                        on_line(line)
                    except Exception:
                        pass
        except Exception:
            pass

    try:
        # CREATE_NO_WINDOW: the server runs windowed and owns no console, so
        # without this every beets import allocates one and a terminal flashes.
        proc = subprocess.Popen(
            cmd, cwd=REPO_ROOT, env=_env(),
            stdin=subprocess.DEVNULL, stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT, text=True, encoding="utf-8",
            errors="replace", bufsize=1,
            creationflags=0x08000000 if os.name == "nt" else 0,
        )
    except OSError as e:
        return False, f"beets could not start: {e}"
    pump = threading.Thread(target=_reader, args=(proc.stdout,), daemon=True)
    pump.start()
    timed_out = False
    try:
        proc.wait(timeout=timeout)
    except subprocess.TimeoutExpired:
        timed_out = True
        try:
            proc.kill()
            proc.wait(timeout=15)
        except Exception:
            pass
    finally:
        try:
            proc.stdout.close()
        except Exception:
            pass
        pump.join(timeout=5)
    output = "\n".join(tail).strip()
    if timed_out:
        return False, f"beets import timed out after {timeout}s"
    if proc.returncode != 0:
        t = "\n".join(output.splitlines()[-15:])
        return False, f"beets import failed (rc={proc.returncode}):\n{t}"
    return True, output


def _album_audio_state(album_dir):
    """(audio basenames, MusicBrainz release-group-ish identity set) for a
    directory — the identity used to re-unite sidecars with moved audio."""
    from mlo.audio import AudioFile
    from mlo.paths import AUDIO_EXTS
    from mlo.stats import is_audio_file

    basenames, mbids = set(), set()
    try:
        names = os.listdir(album_dir)
    except OSError:
        return basenames, mbids
    for name in names:
        if not is_audio_file(name):
            continue
        basenames.add(name.lower())
        try:
            af = AudioFile(os.path.join(album_dir, name))
            for key in ("MUSICBRAINZ_ALBUMID", "MUSICBRAINZ_RELEASEGROUPID"):
                val = af.get_tag(key)
                if val:
                    mbids.add(str(val).strip().lower())
        except Exception:
            pass
    return basenames, mbids


def _gather_orphaned_artifacts(pre, post_dirs, music_folder):
    """After beets moved an album's audio, its videos / CUE / LOG / cover
    stay behind in the now audio-less source dir. Re-unite them: each
    orphan dir's remaining files move to the fresh album dir that carries
    the same MusicBrainz IDs (fallback: same audio basenames). Returns the
    list of emptied source dirs."""
    import shutil

    from mlo.audio import AudioFile
    from mlo.stats import is_audio_file

    moved_from = []
    for old_dir, state in pre.items():
        if not os.path.isdir(old_dir):
            continue
        if any(is_audio_file(f) for f in os.listdir(old_dir)):
            continue  # audio still here — beets didn't move this album
        leftovers = [f for f in sorted(os.listdir(old_dir)) if not is_audio_file(f)]
        if not leftovers:
            continue
        # find the destination: fresh dir with matching MBIDs / basenames
        dest = None
        for cand in post_dirs:
            cb, cm = _album_audio_state(cand)
            if (state[1] and cm and (state[1] & cm)) or (state[0] and (state[0] & cb)):
                dest = cand
                break
        if not dest or os.path.abspath(dest) == os.path.abspath(old_dir):
            continue
        blocked = 0
        for name in leftovers:
            src = os.path.join(old_dir, name)
            dst = os.path.join(dest, name)
            if os.path.exists(dst):
                blocked += 1
                continue
            try:
                shutil.move(src, dst)
            except Exception:
                blocked += 1
        if not blocked:
            moved_from.append(old_dir)
        # prune the emptied chain up to (not including) the music folder
        try:
            folder_abs = os.path.abspath(music_folder or old_dir)
            d = os.path.abspath(old_dir)
            while d != folder_abs and d.startswith(folder_abs):
                try:
                    os.rmdir(d)
                except OSError:
                    break
                d = os.path.dirname(d)
        except Exception:
            pass
    return moved_from


def run_beets_tagging(config=None):
    """Script 14 — Tag with beets (MusicBrainz, Picard parity).

    Headless ``beet import`` over the target album folders, or the whole
    music folder when no targets are given. Beets writes the full
    Picard-parity tag set and places audio per the naming script. Albums
    whose folder changed leave their videos / CUE / LOG / cover behind
    (beets only imports audio), so those artifacts are gathered into the
    new album dir afterwards; ``beets_organize_after`` additionally
    re-organizes the touched folders. Skips gracefully (stats, no error)
    when beets isn't installed, so Run All works on every machine."""
    import time

    from mlo.stats import _find_albums, new_stats
    from mlo.ui import Color, c, log, print_header

    config = config or load_config()
    stats = new_stats()

    print_header("Beets Tagging (MusicBrainz)")
    if not beets_available():
        log("beets is not installed — skipping (install from Settings → Beets)")
        stats["skipped_count"] = 1
        return stats

    folder = config.get("music_folder") or ""
    targets = config.get("targets")
    if targets:
        paths = [os.path.normpath(p) for p in targets if os.path.isdir(p)]
    else:
        paths = [folder] if os.path.isdir(folder) else []
    if not paths:
        log("No album folders to tag.")
        return stats

    # Pre-import snapshot: which album dirs hold which audio (by name and
    # MusicBrainz IDs), so artifacts left behind by a move can be gathered.
    try:
        scan_before = folder if os.path.isdir(folder) else os.path.commonpath(paths)
    except ValueError:
        scan_before = ""
    pre = {}
    try:
        dirs = _find_albums(scan_before) if os.path.isdir(scan_before) else []
        if targets:
            dirs = sorted(set(dirs) | set(paths))
        for d in dirs:
            pre[d] = _album_audio_state(d)
    except Exception:
        pre = {}

    log(f"importing: {paths[0]}" + (f" (+{len(paths) - 1} more)" if len(paths) > 1 else ""))
    cutoff = time.time()
    # Progress: beets prints one line per item it processes, and that is the
    # only signal a headless import emits. Counting the items up front turns
    # the header's bar into real numbers, so a long MB-lookup phase reads as
    # slow rather than hung (the bar used to sit on the step's name for the
    # whole import — the single biggest step of a Run All).
    import mlo.stats as _stats
    from mlo.paths import LIB_AUDIO_EXTS
    hook = getattr(_stats, "progress_hook", None)
    total_items = 0
    try:
        for d in (list(pre) or paths):
            total_items += sum(1 for f in os.listdir(d)
                               if f.lower().endswith(LIB_AUDIO_EXTS))
    except OSError:
        total_items = 0
    done_items = [0]
    phase = ["MusicBrainz lookup"]

    def _tick(line):
        low = line.strip().lower()
        if not low:
            return
        if low.endswith(LIB_AUDIO_EXTS):
            done_items[0] += 1
        else:
            # beets prints nothing at all during its lookup phase, so the step
            # name sat there alone for the whole import ("stuck on Beets
            # tagging"). Whatever the child does print becomes the step's
            # detail: the header then shows the album/file it is working on,
            # and a run that is genuinely busy can never look hung.
            phase[0] = line.strip()[:80]
        if callable(hook):
            try:
                hook(min(done_items[0], total_items or done_items[0]),
                     total_items or done_items[0],
                     f"Beets tagging — {phase[0]}")
            except Exception:
                pass

    if callable(hook) and total_items:
        try:
            hook(0, total_items, "Beets tagging — looking up on MusicBrainz")
        except Exception:
            pass
    ok, output = run_beets_import(paths, config, on_line=_tick)
    if not ok:
        stats["error_count"] += 1
        stats["errors"].append(output[-500:])
        log(c("beets import failed — see the error detail", Color.RED))
        return stats

    # Albums whose folder mtime moved = freshly (re)tagged / organized.
    scan_root = folder if os.path.isdir(folder) else paths[0]
    fresh = []
    try:
        fresh = [d for d in _find_albums(scan_root)
                 if os.path.getmtime(d) >= cutoff - 1]
    except Exception:
        pass
    stats["modified_count"] = len(fresh)
    # Where the album's audio went. Beets MOVES an album into the library and
    # names every file from the tags, so a chain pointed at the folder it came
    # from (an import's staging folder) cannot recognise it by file name any
    # more — `server.script_runners._follow_moved_targets` reads this to
    # re-point the rest of the chain instead of running the whole tag-writing
    # tail against a folder that no longer holds the album.
    stats["moved_targets"] = list(fresh)

    # Re-unite sidecars / videos / covers beets left in emptied folders.
    gathered = []
    try:
        gathered = _gather_orphaned_artifacts(
            pre, fresh if fresh else [d for d in _find_albums(scan_root)],
            folder)
    except Exception as e:
        stats["errors"].append(f"artifact gathering failed: {e}")
    if gathered:
        for d in gathered:
            log(f"gathered leftovers from {d}")
        stats["skipped_count"] += len(gathered)

    log(c(f"beets import finished — {len(fresh)} album(s) written", Color.GREEN))

    # Organize after beets: beets places audio on the naming script's path
    # (mloplugin's %mlo_dir{$mlo_file}) but leaves videos / CUE / LOG / cover
    # behind, so re-apply the script to the albums it actually touched —
    # this also gathers those sidecars. Idempotent: already-compliant folders
    # are rewritten 0 bytes. Only fresh (touched) dirs are organized — never
    # reorganize compliant folders speculatively.
    if config.get("beets_organize_after", True) and fresh:
        try:
            from server.main import OrganizeRequest, organize
            res = organize(OrganizeRequest(paths=fresh, dry_run=False))
            errs = [r for r in res.get("results", []) if r.get("error")]
            if errs:
                stats["errors"].extend(str(r.get("error")) for r in errs[:5])
                stats["error_count"] += len(errs)
            else:
                log("organize after beets: naming script applied")
        except Exception as e:
            stats["error_count"] += 1
            stats["errors"].append(f"organize after beets failed: {e}")

    return stats
