"""Managed slskd (Soulseek) integration.

slskd (https://github.com/slskd/slskd) is a single-binary Soulseek client
with a REST API. It is vendored into .dependencies like every other tool;
this module:

  * generates slskd's YAML config from MLO settings (credentials, profile
    description, listen/web ports, upload/download limits, shares = the
    music folder, download dir),
  * spawns/monitors the process,
  * exposes a thin REST client (search, downloads, transfers, profile).

The generated config lives at server/data/slskd.yaml; a random web API key
is minted per start and kept in memory (the web UI is bound to localhost).
"""
import os
import re
import subprocess
import threading
import time
import uuid
from urllib.parse import quote

import httpx

from mlo.config import load_config
from mlo.fetchdeps import installed_path
from server.beetscfg import REPO_ROOT

_proc_lock = threading.RLock()  # reentrant: start() holds it while calling is_running()
_proc = {"proc": None, "api_key": None, "started_at": 0.0}

CREATE_NO_WINDOW = 0x08000000


def config_path():
    """slskd.yaml lives in <music folder>/.data with the rest of the state."""
    from mlo.paths import app_data_dir
    return os.path.join(app_data_dir(), "slskd.yaml")


# --------------------------------------------------------------------------- #
# Binary + config
# --------------------------------------------------------------------------- #
def slskd_exe():
    d = installed_path("slskd")
    if d:
        for name in ("slskd.exe", "slskd"):
            p = os.path.join(d, name)
            if os.path.isfile(p):
                return p
    return None


def slskd_installed():
    return slskd_exe() is not None


def _yq(text):
    # slskd (a .NET app) needs NATIVE separators in paths: a forward-slash
    # share root gets concatenated with backslashes internally ("F:/x\y"),
    # which fails the share scan with "Only absolute paths may be specified"
    # and silently shares no files. Normalize before quoting.
    text = str(text)
    if os.name == "nt":
        text = text.replace("/", "\\")
    return '"' + text.replace("\\", "\\\\").replace('"', "'") + '"'


def download_dir(cfg=None):
    """Where slskd saves files (<music folder>/.mlo_downloads by default)."""
    cfg = cfg or load_config()
    d = str(cfg.get("soulseek_download_dir") or "").strip()
    if d:
        return d
    music = str(cfg.get("music_folder") or "").strip()
    if music:
        return os.path.join(music, ".mlo_downloads")
    from mlo.paths import app_data_dir
    return os.path.join(app_data_dir(), "downloads")


_RESERVED_SHARE_FILTERS = [
    # regex filters applied on top of every share config — the app's own
    # state/transient folders must never be shared to the network
    "'\\.mlo_trash'",
    "'\\.mlo_downloads'",
    "'\\.data'",
    "'(^|[\\\\/])Data([\\\\/]|$)'",
    "'(^|[\\\\/])\\.data([\\\\/]|$)'",
]


def share_dirs(cfg=None):
    """Folders shared to the Soulseek network (default: the music folder)."""
    cfg = cfg or load_config()
    dirs = [str(d).strip() for d in (cfg.get("soulseek_share_dirs") or []) if str(d).strip()]
    music = str(cfg.get("music_folder") or "").strip()
    if not dirs and music:
        dirs = [music]
    return dirs


def share_exclude(cfg=None):
    """Extra share exclude regexes from settings, on top of the reserved ones."""
    cfg = cfg or load_config()
    extra = [str(x).strip() for x in (cfg.get("soulseek_share_exclude") or []) if str(x).strip()]
    return _RESERVED_SHARE_FILTERS + [f"'{x}'" for x in extra]


def generate_yaml(cfg=None):
    """Render slskd config; returns (yaml_text, api_key)."""
    cfg = cfg or load_config()
    api_key = uuid.uuid4().hex
    username = str(cfg.get("soulseek_username") or "").strip()
    password = str(cfg.get("soulseek_password") or "").strip()
    description = str(cfg.get("soulseek_description") or "").strip()
    listen_port = int(cfg.get("soulseek_listen_port") or 50000)
    web_port = int(cfg.get("soulseek_web_port") or 5030)
    up_limit = int(cfg.get("soulseek_up_limit") or 0)
    down_limit = int(cfg.get("soulseek_down_limit") or 0)
    downloads = download_dir(cfg)
    shared = share_dirs(cfg)
    exclude = share_exclude(cfg)

    lines = [
        "# Generated by la musica — edits are overwritten.",
        "web:",
        f"  port: {web_port}",
        "  authentication:",
        "    disabled: true",
        "    api_keys:",
        "      mlo:",
        f"        key: {api_key}",
        "        role: readwrite",
    ]
    if username:
        lines += [
            "authentication:",
            f"  username: {_yq(username)}",
            f"  password: {_yq(password)}",
        ]
    lines += [
        "soulseek:",
        f"  username: {_yq(username)}",
        f"  password: {_yq(password)}",
        f"  description: {_yq(description)}",
        "  listen_ip_address: 0.0.0.0",
        f"  listen_port: {listen_port}",
        f"  global_upload_limit: {up_limit}",
        f"  global_download_limit: {down_limit}",
        "dirs:",
        f"  downloads: {_yq(downloads)}",
        f"  incomplete: {_yq(os.path.join(downloads, '.incomplete'))}",
    ]
    if shared and cfg.get("soulseek_share_library", True):
        lines += ["shares:", "  directories:"]
        lines += [f"    - {_yq(d)}" for d in shared]
        lines.append("  filters:")
        lines += [f"    - {x}" for x in exclude]
    text = "\n".join(lines) + "\n"
    return text, api_key


def write_config(cfg=None):
    text, api_key = generate_yaml(cfg)
    path = config_path()
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    os.replace(tmp, path)
    return api_key


# --------------------------------------------------------------------------- #
# Process management
# --------------------------------------------------------------------------- #
def is_running():
    with _proc_lock:
        proc = _proc["proc"]
        if proc is None:
            return False
        if proc.poll() is not None:
            _proc["proc"] = None
            return False
        return True


def _web_status(cfg=None):
    """Response of GET /application on the configured slskd port (None when
    nothing answers there)."""
    try:
        with httpx.Client(base_url=_base_url(cfg), timeout=1.0) as client:
            return client.get("/application", headers={"Accept": "application/json"})
    except Exception:
        return None

def web_up(cfg=None):
    """True when an slskd web API answers openly on our port."""
    r = _web_status(cfg)
    return r is not None and r.status_code == 200

def _auth_required(cfg=None):
    """True when that API demands authentication.

    Our config disables web auth on localhost, so an answer of 401/403 comes
    from ANOTHER app's slskd (they share the default port 5030). Such a
    listener must never be adopted as ours, and never be killed by Stop.
    """
    r = _web_status(cfg)
    return r is not None and r.status_code in (401, 403)

def instance_owner(cfg=None):
    """Who is answering on the slskd web port? -> (ours, username, why).

    Adopting a foreign instance made the UI report "running, not logged in"
    forever: its API either needs authentication or serves another Soulseek
    account. `why` carries a human explanation whenever it is not ours.
    """
    cfg = cfg or load_config()
    p = int(cfg.get("soulseek_web_port") or 5030)
    want = str(cfg.get("soulseek_username") or "").strip()
    r = _web_status(cfg)
    if r is None:
        return False, None, ""  # nothing listening on our port
    if r.status_code in (401, 403):
        return False, None, (f"another application's slskd is already using "
                             f"port {p} (it requires authentication)")
    if r.status_code != 200:
        return False, None, f"port {p} is used by another program (HTTP {r.status_code})"
    try:
        got = str(((r.json() or {}).get("user") or {}).get("username") or "").strip()
    except Exception:
        got = ""
    if want and got and got.lower() != want.lower():
        return False, got, (f"another application's slskd is already using "
                            f"port {p} (signed in as {got})")
    return True, (got or None), ""


def _last_log_line(path, limit=220):
    """Last non-empty line of a log file ("" when unreadable/empty)."""
    try:
        with open(path, "rb") as f:
            lines = [l.strip() for l in
                     f.read().decode("utf-8", "replace").splitlines() if l.strip()]
        return lines[-1][-limit:] if lines else ""
    except OSError:
        return ""

def start(cfg=None):
    """Spawn slskd; returns (started, message). Idempotent.

    If an slskd from a previous backend run is still answering on the web
    port (orphaned child), it is adopted instead of spawning a duplicate.
    """
    with _proc_lock:
        if is_running():
            return True, "already running"
        exe = slskd_exe()
        if not exe:
            return False, "slskd is not installed"
        # slskd 0.26's single-file zip ships no wwwroot; it refuses to boot
        # without it even though only the REST API is needed here.
        try:
            os.makedirs(os.path.join(os.path.dirname(exe), "wwwroot"), exist_ok=True)
        except OSError:
            pass
        api_key = write_config(cfg)
        # Adopt an already-listening slskd, but ONLY our own. A foreign one
        # (another app's slskd on the same port) must not be adopted: its
        # API rejects us and Stop would kill a process we do not own.
        ours, _who, why = instance_owner(cfg)
        if ours:
            _proc["api_key"] = None
            _proc["started_at"] = time.time()
            return True, "adopted already-running slskd"
        if why:
            return False, f"cannot start slskd: {why} — stop the other slskd " \
                           f"first (only one slskd can run at a time)"
        kwargs = {}
        if os.name == "nt":
            kwargs["creationflags"] = CREATE_NO_WINDOW
        log = os.path.join(os.path.dirname(config_path()), "slskd.log")
        try:
            logf = open(log, "wb")
        except OSError:
            logf = subprocess.DEVNULL
        proc = subprocess.Popen(
            [exe, "--config", config_path(), "--no-logo"],
            cwd=os.path.dirname(exe),
            stdout=logf,
            stderr=subprocess.STDOUT,
            **kwargs,
        )
        if hasattr(logf, "close"):
            logf.close()  # the child keeps its own handle
        # slskd allows ONE instance per machine. When another slskd is
        # already running, this one exits at once and the UI used to look
        # like a dead "Start" button for ever. Report what it actually said.
        deadline = time.time() + 2.0
        while time.time() < deadline and proc.poll() is None:
            time.sleep(0.1)
        if proc.poll() is not None:
            detail = _last_log_line(log)
            raise_msg = (f"slskd exited immediately ({detail}) — only one slskd "
                         f"can run at a time, so stop the other app's slskd first"
                         if detail else
                         "slskd exited immediately — another slskd is probably "
                         "already running on this machine")
            return False, raise_msg
        _proc["proc"] = proc
        _proc["api_key"] = api_key
        _proc["started_at"] = time.time()
        return True, "started"


def _kill_port_listener(port):
    """Hard-kill whatever process listens on the slskd web port.

    Needed for ADOPTED slskd instances (spawned by a previous backend run):
    no child handle exists, so a plain terminate is impossible and the
    process would otherwise keep running after the user presses Stop."""
    try:
        if os.name == "nt":
            out = subprocess.run(
                ["netstat", "-ano", "-p", "TCP"],
                capture_output=True, text=True, timeout=10,
            ).stdout
            pids = set()
            for ln in out.splitlines():
                parts = ln.split()
                if len(parts) >= 5 and parts[3].upper() == "LISTENING" and f":{port} " in ln:
                    pids.add(parts[-1])
            killed = False
            for pid in pids:
                if pid.isdigit() and pid != "0":
                    subprocess.run(["taskkill", "/F", "/PID", pid],
                                   capture_output=True, timeout=10)
                    killed = True
            return killed
        r = subprocess.run(["fuser", "-k", f"{port}/tcp"],
                           capture_output=True, timeout=10)
        return r.returncode == 0
    except Exception:
        return False


def stop(cfg=None):
    cfg = cfg or load_config()
    port = int(cfg.get("soulseek_web_port") or 5030)
    with _proc_lock:
        proc = _proc["proc"]
        _proc["proc"] = None
        if proc is None or proc.poll() is not None:
            # untracked (adopted) slskd — the only way down is via the port.
            # Never kill a listener that demands authentication: that is
            # another app's slskd (see instance_owner).
            if web_up(cfg) and not _auth_required(cfg):
                return _kill_port_listener(port)
            return False
        try:
            proc.terminate()
            try:
                proc.wait(timeout=3)
            except subprocess.TimeoutExpired:
                proc.kill()
                proc.wait(timeout=3)
        except OSError:
            pass
    # a straggler or adopted sibling can still hold the web port
    time.sleep(0.3)
    if web_up(cfg) and not _auth_required(cfg):
        _kill_port_listener(port)
    return True


# --------------------------------------------------------------------------- #
# REST client (slskd /api/v0)
# --------------------------------------------------------------------------- #
def _base_url(cfg=None):
    cfg = cfg or load_config()
    web_port = int(cfg.get("soulseek_web_port") or 5030)
    return f"http://127.0.0.1:{web_port}/api/v0"


def _headers():
    key = _proc["api_key"]
    h = {"Accept": "application/json"}
    if key:
        h["X-API-Key"] = key
    return h


def _request(method, path, json_body=None, timeout=30.0):
    with httpx.Client(base_url=_base_url(), timeout=timeout) as client:
        r = client.request(method, path, json=json_body, headers=_headers())
        if r.status_code in (401, 403) and _proc["api_key"]:
            # stale key from a previous slskd boot — the running instance
            # mints its own; retry anonymously (auth is localhost-only)
            _proc["api_key"] = None
            r = client.request(method, path, json=json_body, headers=_headers())
        r.raise_for_status()
        if r.status_code == 204 or not r.content:
            return None
        return r.json()


def wait_until_ready(timeout=25.0):
    """Poll the slskd application info endpoint until it answers."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            _request("GET", "/application", timeout=2.0)
            return True
        except Exception:
            time.sleep(0.25)
    return False


# --------------------------------------------------------------------------- #
# High-level operations
# --------------------------------------------------------------------------- #
def search(query, cfg=None, timeout_ms=None):
    """Start a search; returns the search id for polling.

    slskd validates a client-supplied id as a GUID — older builds ignored
    it, current ones answer 400 to anything else (which broke every search).
    A real GUID is sent; if still refused, retry without one and use
    whatever id slskd assigned. timeout_ms extends the search duration per
    request (slskd's own default is short, which starves slow networks)."""
    search_id = str(uuid.uuid4())
    body = {"id": search_id, "searchText": query}
    if timeout_ms:
        # slskd's DTO field is SearchTimeout; a "timeout" key is ignored.
        body["searchTimeout"] = int(timeout_ms)
    try:
        resp = _request("POST", "/searches", json_body=body, timeout=30.0)
    except httpx.HTTPStatusError as e:
        if e.response is None or e.response.status_code != 400:
            raise
        body.pop("id", None)
        resp = _request("POST", "/searches", json_body=body, timeout=30.0)
    remote = str((resp or {}).get("id") or "").strip()
    return remote or search_id


def is_search_done(res_or_state):
    """True when an slskd search has completed, timed out, or cancelled.

    slskd states are bitwise flags that serialize to comma-separated strings
    like 'Completed, TimedOut' or 'InProgress'.
    """
    if isinstance(res_or_state, dict):
        if res_or_state.get("isComplete"):
            return True
        st = res_or_state.get("state")
    else:
        st = res_or_state
    if not st or st == "InProgress":
        return False
    return any(x in str(st) for x in ("Completed", "TimedOut", "ResponseLimitReached", "Cancelled"))


def search_results(search_id, cfg=None):
    """Aggregate file responses for a finished/in-progress search."""
    try:
        state = _request("GET", f"/searches/{search_id}")
    except httpx.HTTPStatusError as e:
        if e.response is not None and e.response.status_code == 404:
            return {
                "state": "NotFound",
                "isComplete": True,
                "responseCount": 0,
                "fileCount": 0,
                "responses": [],
            }
        raise
    responses = []
    try:
        resp_list = _request("GET", f"/searches/{search_id}/responses") or []
    except httpx.HTTPStatusError as e:
        if e.response is not None and e.response.status_code == 404:
            resp_list = []
        else:
            raise
    for r in resp_list or []:
        username = r.get("username") or ""
        slot = bool(r.get("hasFreeUploadSlot"))
        speed = int(r.get("uploadSpeed") or 0)
        queue = int(r.get("queueLength") or 0)
        for f in r.get("files") or []:
            responses.append({
                "username": username,
                "file": f.get("filename") or "",
                "size": int(f.get("size") or 0),
                "bitrate": f.get("bitrate"),
                "duration": f.get("duration"),
                "vbr": f.get("vbr"),
                "slot": slot,
                "speed": speed,
                "queue": queue,
            })
    st_dict = state if isinstance(state, dict) else {}
    return {
        "state": st_dict.get("state"),
        "isComplete": bool(st_dict.get("isComplete")),
        "responseCount": int(st_dict.get("responseCount") or 0),
        "fileCount": int(st_dict.get("fileCount") or 0),
        "responses": responses,
    }


def enqueue_download(username, files, cfg=None):
    """Queue files for download: files = [{filename, size}].

    slskd's enqueue route is per-user (POST /transfers/downloads/{username})
    with a bare list body — there is no top-level /downloads route."""
    body = [{"filename": f["filename"], "size": int(f.get("size") or 0)}
            for f in files]
    _request("POST", f"/transfers/downloads/{quote(str(username), safe='')}",
             json_body=body, timeout=30.0)
    return True


def downloads_state(cfg=None):
    """Full download transfer tree, grouped per user."""
    try:
        return _request("GET", "/transfers/downloads") or []
    except httpx.HTTPStatusError as e:
        if e.response is not None and e.response.status_code == 404:
            return []
        raise


def uploads_state(cfg=None):
    """Full upload transfer tree (what others have downloaded = shared
    history), grouped per user. Same shape as downloads_state()."""
    try:
        return _request("GET", "/transfers/uploads") or []
    except httpx.HTTPStatusError as e:
        if e.response is not None and e.response.status_code == 404:
            return []
        raise


def server_state(cfg=None):
    """Login status + server stats (or None when logged out)."""
    try:
        return _request("GET", "/server")
    except httpx.HTTPStatusError as e:
        if e.response is not None and e.response.status_code in (401, 403, 404, 503):
            return None
        raise


def user_info(username, cfg=None):
    """Remote user profile (speeds, slots, files shared)."""
    return _request("GET", f"/users/{username}/info", timeout=15.0)


def browse(username, cfg=None):
    """List every shared directory of a remote user (files with sizes)."""
    return _request("GET", f"/users/{username}/browse", timeout=60.0) or []


def restart(cfg=None):
    """Restart slskd so it re-reads its config and re-scans shares.

    slskd indexes shares at boot; new/removed/renamed files in the library
    are only visible to other users after a restart (older slskd builds
    have no share-rescan API). Returns True when slskd answers again.
    """
    stop()
    ok, _msg = start(cfg)
    if not ok:
        return False
    return wait_until_ready(timeout=40.0)


def application_info(cfg=None):
    return _request("GET", "/application", timeout=5.0)


def shares_state(cfg=None):
    """slskd's live share configuration + scan state (None when down)."""
    try:
        return _request("GET", "/shares", timeout=10.0)
    except httpx.HTTPStatusError as e:
        if e.response is not None and e.response.status_code in (401, 403, 404, 503):
            return None
        raise


def rescan_shares(cfg=None):
    """Ask slskd to rescan its share index (PUT /shares)."""
    _request("PUT", "/shares", timeout=30.0)
    return True


# --------------------------------------------------------------------------- #
# Importing completed downloads into the library
# --------------------------------------------------------------------------- #
def import_completed(cfg=None):
    """Move completed downloads into the music folder, one album per folder.

    slskd lays out downloads as <download dir>/<user>/<remote folder>/file.
    Each remote folder becomes an album folder in the library; loose files
    are gathered into a "Soulseek" album folder. Returns the list of new
    album paths.
    """
    import shutil

    cfg = cfg or load_config()
    folder = str(cfg.get("music_folder") or "").strip()
    if not folder or not os.path.isdir(folder):
        raise ValueError("music_folder not set or not found")
    ddir = download_dir(cfg)
    if not os.path.isdir(ddir):
        return []

    def unique_album_dir(name):
        safe = re.sub(r'[<>:"/\\|?*\x00-\x1f]', "", str(name)).strip().rstrip(".")
        dest = os.path.join(folder, safe or "Soulseek Download")
        n = 2
        while os.path.exists(dest):
            dest = os.path.join(folder, f"{safe} ({n})")
            n += 1
        return dest

    moved = []
    for user in sorted(os.listdir(ddir)):
        upath = os.path.join(ddir, user)
        if not os.path.isdir(upath):
            continue
        subs = [s for s in sorted(os.listdir(upath))
                if os.path.isdir(os.path.join(upath, s))]
        if subs:
            # one album per shared folder
            for s in subs:
                dest = unique_album_dir(s)
                shutil.move(os.path.join(upath, s), dest)
                moved.append(dest)
            # leftover loose files from this user -> their own album folder
            leftovers = [f for f in os.listdir(upath)
                         if os.path.isfile(os.path.join(upath, f))]
            if leftovers:
                dest = unique_album_dir(f"Soulseek {user}")
                os.makedirs(dest)
                for f in leftovers:
                    shutil.move(os.path.join(upath, f), os.path.join(dest, f))
                moved.append(dest)
            os.rmdir(upath)
        else:
            # user dir with only loose files -> single album folder
            dest = unique_album_dir(f"Soulseek {user}")
            shutil.move(upath, dest)
            moved.append(dest)
    # legacy layout: loose files directly in the download root
    loose = [f for f in sorted(os.listdir(ddir))
             if os.path.isfile(os.path.join(ddir, f))]
    if loose:
        dest = unique_album_dir("Soulseek")
        os.makedirs(dest)
        for f in loose:
            shutil.move(os.path.join(ddir, f), os.path.join(dest, f))
        moved.append(dest)
    return moved
