#!/usr/bin/env python3
"""One cookie import for every cookie login: filtering, notes, per-cookie list.

Every claim below is about the real code, not a copy of it:

  * an import keeps only the cookies the credential is SENT to (a browser
    extension exports the whole profile) and reports how many cookie lines
    stayed out; a file with nothing for that credential is REFUSED in the
    provider's own words rather than stored — the yt-dlp jar by the endpoint
    that writes it, RYM by storing nothing and saying why;
  * a per-cookie comment is keyed by the cookie's IDENTITY (domain, path,
    name), not by position: it survives a re-import that re-orders the file,
    and a same-named cookie on another domain keeps its own (empty) comment;
  * writing a comment never touches the cookie data: the jar's cookie lines
    are byte for byte what they were, and parsing the file with comments back
    yields the identical cookie set — the note rides in a `# mlo-comment:`
    line, which every Netscape reader skips (yt-dlp included);
  * the note round-trips through the FILE: a jar this app wrote carries its
    comments, and importing it again (into a config that lost them) brings
    them back, keyed the same way;
  * `GET/POST /api/cookies/{source}` are the panel's one idiom for both
    credentials (domain, path, name, expiry, expired, comment), they refuse an
    unknown source and a comment for a cookie the source does not hold, and no
    answer of theirs ever carries a cookie VALUE;
  * an expired export is named as expired — the failure that otherwise looks
    green: the jar parses, the panel is happy, and the provider answers as a
    guest.

Hermetic: the music folder is redirected to a temp dir (MLO_MUSIC_FOLDER) and
mlo.config/mlo.paths' CONFIG_FILE to a temp stub, so the jar under test is
<tmp>/Music/.mlo/data/cookies.txt and the real install's app state, config.json
and cookies are never read, written or deleted. No network is used.

Run:  python tools/test_cookie_import.py
"""
import json
import os
import shutil
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

OUT = os.environ.pop("MLO_MUSIC_FOLDER", None)  # keep the test hermetic

tmp = tempfile.mkdtemp(prefix="mlo_cookieimport_")
music = os.path.join(tmp, "Music")
os.makedirs(music)
os.environ["MLO_MUSIC_FOLDER"] = music

import mlo.config as cfgmod  # noqa: E402
import mlo.paths as pathmod  # noqa: E402

stub_config = os.path.join(tmp, "config.json")
_real_config_files = {mod: mod.CONFIG_FILE for mod in (cfgmod, pathmod)}
for _mod in (cfgmod, pathmod):
    _mod.CONFIG_FILE = stub_config

from fastapi import HTTPException  # noqa: E402

from server import api_cookies, api_rym, api_youtube  # noqa: E402
from server import cookies as cookie_mod  # noqa: E402

HEADER = "# Netscape HTTP Cookie File\n"
JAR = os.path.join(music, ".mlo", "data", "cookies.txt")

# The cookie lines the fixtures share, named so a test can point at the exact
# line a note must (or must not) sit above.
YT_SID = ".youtube.com\tTRUE\t/\tTRUE\t1893456000\tSID\tYT-VALUE\n"
GOOGLE_SID = ".google.com\tTRUE\t/\tTRUE\t1893456000\tSID\tG-VALUE\n"
GOOGLE_NID = ".google.com\tTRUE\t/\tTRUE\t1893456000\tNID\t523=abc\n"
OTHER_SITE = ".example.com\tTRUE\t/\tFALSE\t1893456000\ttracking\tNOPE-VALUE\n"

# A browser extension's export: the header, one cookie per site the profile is
# signed in to — including two cookies that share one NAME on two domains,
# which is what a comment keyed by position would confuse — plus a site this
# jar is never sent to.
PROFILE = (HEADER
           + "# This file was generated by a browser extension.  Do not edit.\n"
           + "\n" + YT_SID + GOOGLE_NID + GOOGLE_SID + OTHER_SITE)

# What the YouTube jar must hold afterwards: the same file minus the other
# site's line, byte for byte (comments and all).
FILTERED = (HEADER
            + "# This file was generated by a browser extension.  Do not edit.\n"
            + "\n" + YT_SID + GOOGLE_NID + GOOGLE_SID)

# The same three cookies in the OPPOSITE order: a re-export of the same
# profile, which is what a positional comment would lose.
REORDERED = HEADER + GOOGLE_SID + GOOGLE_NID + YT_SID

# Google's cookies and nothing for YouTube: a signed-in Google profile, not a
# YouTube session. Storing it would leave a green panel over a download that
# still asks the user to sign in.
GOOGLE_ONLY = HEADER + GOOGLE_NID

# And the mirror case for RYM: a file with no rateyourmusic.com cookie in it.
YOUTUBE_ONLY = HEADER + YT_SID

# A session cookie that expired years ago: the export that "just stopped
# working".
EXPIRED = HEADER + ".youtube.com\tTRUE\t/\tTRUE\t1000000000\tSID\tYT-OLD\n"

# RYM's own export: the HttpOnly session cookie (the reason the import exists)
# next to the Cloudflare one, with YouTube's cookies in the same profile.
RYM_SESSION = "#HttpOnly_.rateyourmusic.com\tTRUE\t/\tTRUE\t1893456000\tsession\tRYM-VALUE\n"
RYM_CLEARANCE = ".rateyourmusic.com\tTRUE\t/\tTRUE\t1893456000\tcf_clearance\tCF-VALUE\n"
RYM_PROFILE = HEADER + RYM_SESSION + RYM_CLEARANCE + YT_SID

# The cookie VALUES in the fixtures: none may ever appear in an API answer.
SECRETS = ["YT-VALUE", "G-VALUE", "NOPE-VALUE", "YT-OLD", "RYM-VALUE",
           "CF-VALUE", "523=abc"]


def assert_no_values(payload, where):
    """The answer is columns, counts and sentences — never a cookie value."""
    blob = json.dumps(payload)
    for secret in SECRETS:
        assert secret not in blob, f"{where} leaked a cookie value: {blob}"


def jar_text():
    with open(JAR, encoding="utf-8") as fh:
        return fh.read()


def note_above(text, cookie_line):
    """The `# mlo-comment:` note written directly above *cookie_line*, or ""."""
    lines = text.split("\n")
    index = lines.index(cookie_line.rstrip("\n")) if cookie_line.rstrip("\n") in lines else -1
    if index <= 0:
        return ""
    above = lines[index - 1]
    return above[len(cookie_mod.COMMENT_MARK):] if above.startswith(cookie_mod.COMMENT_MARK) else ""


def cookie_data(text):
    """[(domain, path, name, value)] — the file's cookie data, as parsed."""
    records, error = cookie_mod.parse_cookies(text)
    assert error is None, error
    return [(c.domain, c.path, c.name, c.value) for c in records]


def without_notes(text):
    """The file with our own note lines removed (the cookie data, verbatim)."""
    return "\n".join(line for line in text.split("\n")
                     if not line.startswith(cookie_mod.COMMENT_MARK))


def post_youtube(text):
    return api_youtube.youtube_cookies_post(api_youtube.CookieUpload(text=text))


def post_rym(text):
    return api_rym.rym_cookies_post(api_rym.CookieUpload(text=text))


def comment(source, domain, path, name, text):
    return api_cookies.cookies_comment(
        source, api_cookies.CookieComment(domain=domain, path=path, name=name,
                                          comment=text))


def row(state, name, domain):
    """One cookie of a per-cookie answer, matched on BOTH domain and name."""
    for item in state["cookies"]:
        if item["name"] == name and item["domain"] == domain:
            return item
    raise AssertionError(f"{domain} {name} is not in {state}")


def refused(fn, status, want):
    """The HTTPException *fn* raises, with *want* in its sentence."""
    try:
        fn()
    except HTTPException as e:
        assert e.status_code == status, (e.status_code, e.detail)
        assert want in e.detail, e.detail
        return e.detail
    raise AssertionError(f"nothing was refused (wanted {want!r})")


try:
    # ----------------------------------------------------------------- #
    # 1. The import keeps what the credential is sent, nothing else
    # ----------------------------------------------------------------- #
    saved = post_youtube(PROFILE)
    assert saved["lines"] == 3, saved
    assert saved["sites"] == ["google.com", "youtube.com"], saved
    assert saved["filtered"] == 1, saved  # `.example.com`, and only that
    assert saved["warnings"], saved
    assert_no_values(saved, "the YouTube import's answer")
    # A browser profile's export is narrowed to the hosts yt-dlp is given this
    # jar for: the file is the paste minus the OTHER site's line, byte for byte
    # (its own comment lines and all).
    assert jar_text() == FILTERED, jar_text()
    assert JAR.replace("\\", "/").endswith("/Music/.mlo/data/cookies.txt"), JAR
    assert pathmod.CONFIG_FILE == stub_config, pathmod.CONFIG_FILE

    # A file for sites this jar is NOT for is refused, in YouTube's terms, and
    # the jar that was working is left exactly as it was.
    detail = refused(lambda: post_youtube(GOOGLE_ONLY), 400,
                     "no youtube.com cookie in this file")
    assert "sign in to YouTube" in detail, detail
    assert jar_text() == FILTERED, "a refused import replaced the jar"

    # An export whose cookies have already expired says so: the failure that
    # otherwise looks exactly like a working jar.
    saved = post_youtube(EXPIRED)
    assert any("expired" in w for w in saved["warnings"]), saved["warnings"]
    assert len(saved["warnings"]) == 2, saved["warnings"]  # holds one, warns twice

    # ----------------------------------------------------------------- #
    # 2. One comment per cookie, keyed by identity, not by position
    # ----------------------------------------------------------------- #
    post_youtube(PROFILE)
    # The two SIDs share a NAME on two domains: the comment goes on the GOOGLE
    # one, and the YouTube one must stay untouched — that is the whole reason
    # the note is keyed by identity instead of by line number.
    state = comment("youtube", "google.com", "/", "SID", "my other account")
    assert row(state, "SID", "google.com")["comment"] == "my other account", state
    assert row(state, "SID", "youtube.com")["comment"] == "", state
    assert_no_values(state, "the comment's answer")
    on_disk = jar_text()
    assert note_above(on_disk, GOOGLE_SID) == "my other account", on_disk
    assert note_above(on_disk, YT_SID) == "", on_disk
    assert note_above(on_disk, GOOGLE_NID) == "", on_disk
    # The cookie DATA is byte for byte what it was: writing a note changes the
    # file's comments and NOTHING else, so a jar written with comments still
    # parses to the identical cookie set (and yt-dlp still reads it).
    assert without_notes(on_disk) == FILTERED, on_disk
    assert cookie_data(on_disk) == cookie_data(FILTERED), "a note changed the cookies"

    # A RE-IMPORT of the same profile in another order keeps the comment on the
    # cookie it was written for.
    saved = post_youtube(REORDERED)
    assert saved["lines"] == 3, saved
    state = api_cookies.cookies_get("youtube")
    assert row(state, "SID", "google.com")["comment"] == "my other account", state
    assert row(state, "SID", "youtube.com")["comment"] == "", state
    on_disk = jar_text()
    assert note_above(on_disk, GOOGLE_SID) == "my other account", on_disk
    assert note_above(on_disk, YT_SID) == "", on_disk

    # Editing one comment leaves the others alone; an empty one clears it.
    comment("youtube", "youtube.com", "/", "SID", "the main one")
    state = api_cookies.cookies_get("youtube")
    assert row(state, "SID", "google.com")["comment"] == "my other account", state
    assert row(state, "SID", "youtube.com")["comment"] == "the main one", state
    state = comment("youtube", "google.com", "/", "SID", "")
    assert row(state, "SID", "google.com")["comment"] == "", state
    assert row(state, "SID", "youtube.com")["comment"] == "the main one", state
    on_disk = jar_text()
    assert "my other account" not in on_disk, on_disk
    assert note_above(on_disk, YT_SID) == "the main one", on_disk
    assert note_above(on_disk, GOOGLE_SID) == "", on_disk

    # The expiry column the file stated is per cookie, and the panel is told
    # whether it has passed — and, for a date it can name, when it dies.
    assert row(state, "NID", "google.com")["expiry"] == "1893456000", state
    assert row(state, "NID", "google.com")["expires_at"] == "2030-01-01", state
    assert row(state, "NID", "google.com")["expired"] is False, state
    assert row(state, "SID", "youtube.com")["path"] == "/", state
    assert_no_values(state, "the per-cookie list")

    # ----------------------------------------------------------------- #
    # 3. The note round-trips through the jar itself
    # ----------------------------------------------------------------- #
    written = jar_text()
    assert cookie_mod.jar_comments(written) == {"youtube.com\t/\tSID": "the main one"}, \
        cookie_mod.jar_comments(written)
    # A jar this app wrote states its own notes: importing it into a config that
    # no longer knows them brings them back, keyed the same way.
    cfg = cfgmod.load_config()
    cfg["cookie_notes"] = ""
    assert cfgmod.save_config(cfg), "could not clear the notes store"
    assert [c["comment"] for c in api_cookies.cookies_get("youtube")["cookies"]] == \
        ["", "", ""], "a cleared store still answered with a comment"
    post_youtube(written)
    assert row(api_cookies.cookies_get("youtube"),
               "SID", "youtube.com")["comment"] == "the main one", jar_text()

    # A comment that would break the FILE (a newline, or a small novel) is
    # flattened and capped rather than written into it.
    state = comment("youtube", "youtube.com", "/", "SID",
                    "line one\nline two" + "x" * 500)
    assert "\n" not in row(state, "SID", "youtube.com")["comment"], state
    assert len(row(state, "SID", "youtube.com")["comment"]) == \
        cookie_mod.MAX_COMMENT_CHARS, state
    assert len(jar_text().splitlines()) == len(REORDERED.splitlines()) + 1, \
        "a comment line was written for the wrong cookie"
    assert cookie_data(jar_text()) == cookie_data(REORDERED), "a long note changed the cookies"
    comment("youtube", "youtube.com", "/", "SID", "the main one")

    # ----------------------------------------------------------------- #
    # 4. The same view for RYM, whose credential is a header, not a file
    # ----------------------------------------------------------------- #
    saved = post_rym(RYM_PROFILE)
    assert saved["stored"] == 2 and saved["session"] is True, saved
    assert saved["filtered"] == 1, saved  # the youtube.com cookie in the file
    assert_no_values(saved, "the RYM import's answer")
    assert cfgmod.load_config()["rym_cookie"] == \
        "session=RYM-VALUE; cf_clearance=CF-VALUE"
    state = api_cookies.cookies_get("rym")
    assert state["present"] is True and len(state["cookies"]) == 2, state
    assert state["hosts"] == ["rateyourmusic.com"], state
    assert [c["name"] for c in state["cookies"]] == ["session", "cf_clearance"], state
    assert_no_values(state, "RYM's per-cookie view")
    # The header has nowhere to carry the expiry, so the import REMEMBERED what
    # the file stated — the panel can still say when the session dies.
    assert row(state, "session", "rateyourmusic.com")["expiry"] == "1893456000", state
    assert row(state, "session", "rateyourmusic.com")["expires_at"] == "2030-01-01", state

    state = comment("rym", "rateyourmusic.com", "/", "session", "the signed-in one")
    assert row(state, "session", "rateyourmusic.com")["comment"] == "the signed-in one", state
    assert row(state, "cf_clearance", "rateyourmusic.com")["comment"] == "", state
    assert_no_values(state, "RYM's comment answer")
    # The credential itself is untouched by a comment: RYM is still sent the
    # exact header the import stored.
    assert cfgmod.load_config()["rym_cookie"] == \
        "session=RYM-VALUE; cf_clearance=CF-VALUE"

    # A re-import (the same cookies, another order) keeps the comment and
    # refreshes the expiries without losing the user's note.
    saved = post_rym(HEADER + RYM_CLEARANCE + RYM_SESSION)
    assert saved["stored"] == 2, saved
    state = api_cookies.cookies_get("rym")
    assert row(state, "session", "rateyourmusic.com")["comment"] == "the signed-in one", state
    assert [c["name"] for c in state["cookies"]] == ["cf_clearance", "session"], state

    # A file with no RYM cookie still stores nothing and says why, so the
    # credential that was working survives it.
    before = cfgmod.load_config()["rym_cookie"]
    saved = post_rym(YOUTUBE_ONLY)
    assert saved["stored"] == 0 and saved["filtered"] == 1, saved
    assert "rateyourmusic.com" in saved["warnings"][0], saved
    assert cfgmod.load_config()["rym_cookie"] == before, \
        "a foreign jar replaced RYM's cookie"

    # Clearing the comment leaves the remembered expiry in place (it describes
    # the cookie, not the note).
    state = comment("rym", "rateyourmusic.com", "/", "session", "")
    assert row(state, "session", "rateyourmusic.com")["comment"] == "", state
    assert row(state, "session", "rateyourmusic.com")["expiry"] == "1893456000", state
    notes = json.loads(cfgmod.load_config()["cookie_notes"])
    assert notes["rym"]["rateyourmusic.com\t/\tsession"] == {"expiry": "1893456000"}, notes
    assert notes["rym"]["rateyourmusic.com\t/\tcf_clearance"] == {"expiry": "1893456000"}, notes
    # …and the yt-dlp jar's notes are a different slice of the same store, with
    # the comment the user wrote and no expiry of their own to remember.
    assert notes["youtube"]["youtube.com\t/\tSID"] == {"comment": "the main one"}, notes

    # ----------------------------------------------------------------- #
    # 5. The route refuses what it cannot attach a note to
    # ----------------------------------------------------------------- #
    refused(lambda: api_cookies.cookies_get("bandcamp"), 404,
            "unknown cookie source")
    refused(lambda: comment("rym", "rateyourmusic.com", "/", "nope", "x"),
            404, "no nope cookie")
    refused(lambda: comment("youtube", "youtube.com", "/", "nope", "x"),
            404, "no nope cookie")
    # A cookie on a path the jar does not hold is not that cookie either:
    # identity is domain AND path AND name.
    refused(lambda: comment("youtube", "youtube.com", "/browse", "SID", "x"),
            404, "no SID cookie")

    # Deleting the jar leaves the notes where they are (keyed by identity, so
    # the next import of the same profile finds them again).
    api_youtube.youtube_cookies_delete()
    assert api_cookies.cookies_get("youtube")["cookies"] == []
    assert api_cookies.cookies_get("youtube")["present"] is False
    post_youtube(PROFILE)
    assert row(api_cookies.cookies_get("youtube"),
               "SID", "youtube.com")["comment"] == "the main one", \
        "a comment did not survive the jar being deleted and re-imported"

    print("PASS  cookie import: filtering, per-cookie comments, identity keys, "
          "jar round-trip, both credentials")
finally:
    if OUT:
        os.environ["MLO_MUSIC_FOLDER"] = OUT
    else:
        os.environ.pop("MLO_MUSIC_FOLDER", None)
    for _mod, _path in _real_config_files.items():
        _mod.CONFIG_FILE = _path
    cfgmod._MIGRATED = False
    shutil.rmtree(tmp, ignore_errors=True)
