#!/usr/bin/env python3
"""Cookies for yt-dlp: one jar the app owns, honoured by BOTH of its paths.

Every claim below is about the real code, not a copy of it:

  * the validator accepts a real Netscape cookie file — the sample here is the
    exact format curl/yt-dlp write, header, `#HttpOnly_` domain column and all
    — and refuses junk with the reason it will show the user;
  * the Python API path (yt_dlp.YoutubeDL) receives `cookiefile` /
    `cookiesfrombrowser`, and the BINARY path's argv receives `--cookies <path>`
    / `--cookies-from-browser <name>`. Both are asserted on the options the
    code actually builds — the binary's argv is captured with a stubbed
    `run_tool`, so no yt-dlp process is started here;
  * `none` mode passes NO cookie option at all, on either path: an unset
    setting must not reach yt-dlp as a null/empty value;
  * the endpoints round-trip (save → list → delete) and refuse an oversize
    body before anything is written;
  * the jar the endpoints SAVE is one yt-dlp can actually read: a headerless
    export is completed with the `# Netscape HTTP Cookie File` line (its loader
    refuses a file whose first line is a cookie), and — when `yt_dlp` is
    importable — `yt_dlp.cookies.YoutubeDLCookieJar` really loads the file and
    yields the cookie it was given.

Hermetic: the music folder is redirected to a temp dir (MLO_MUSIC_FOLDER) and
mlo.config/mlo.paths' CONFIG_FILE to a temp stub, so the jar under test is
<tmp>/.mlo/data/cookies.txt and the real install's app state, config.json and
cookies are never read, written or deleted. No network is used.

Run:  python tools/test_youtube_cookies.py
"""
import json
import os
import shutil
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

OUT = os.environ.pop("MLO_MUSIC_FOLDER", None)  # keep the test hermetic

tmp = tempfile.mkdtemp(prefix="mlo_ytcookies_")
music = os.path.join(tmp, "Music")
os.makedirs(music)
os.environ["MLO_MUSIC_FOLDER"] = music

import mlo.config as cfgmod  # noqa: E402
import mlo.paths as pathmod  # noqa: E402

stub_config = os.path.join(tmp, "config.json")
_real_config_files = {mod: mod.CONFIG_FILE for mod in (cfgmod, pathmod)}
for _mod in (cfgmod, pathmod):
    _mod.CONFIG_FILE = stub_config

from fastapi import HTTPException  # noqa: E402

from server import api_youtube, youtube  # noqa: E402

URL = "https://www.youtube.com/watch?v=jNQXAC9IVRw"
JAR = os.path.join(music, ".mlo", "data", "cookies.txt")

# The real thing: the header curl and yt-dlp write, then one line per cookie.
# Columns are domain, include-subdomains, path, secure, expiry, name, value —
# tab separated, which is what makes a jar a jar. `#HttpOnly_` is part of the
# DOMAIN column (a cookie the page's JavaScript must not see), the one
# `#`-prefixed line that carries a cookie rather than a comment.
REAL_JAR = (
    "# Netscape HTTP Cookie File\n"
    "# https://curl.se/docs/http-cookies.html\n"
    "# This file was generated by yt-dlp.  Do not edit.\n"
    "\n"
    ".youtube.com\tTRUE\t/\tTRUE\t1893456000\tLOGIN_INFO\tAFmmF2swRQIgYv\n"
    ".youtube.com\tTRUE\t/\tTRUE\t1893456000\t__Secure-3PSID\tg.a000nQ\n"
    "#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t1893456000\tSID\tg.a000nQ\n"
    ".google.com\tTRUE\t/\tFALSE\t1893456000\tNID\t523=abc\n"
)

# The same shape with no header line at all: browsers' own exporters leave it
# out, so the 7-column shape has to be proof enough on its own.
SHAPED_ONLY = ".youtube.com\tTRUE\t/\tTRUE\t1893456000\tSID\tx\n"

JUNK = [
    ("", "empty"),
    ("just some words\nand more words\n", "not a Netscape cookie file"),
    ('{"cookies": [{"name": "SID"}]}\n', "not a Netscape cookie file"),
    # 7 columns, but the flags are not booleans: a CSV or a log file can look
    # like this by accident, and accepting it would hand yt-dlp a jar that
    # fails to parse on the next download.
    (".youtube.com\tMAYBE\t/\tTRUE\t1893456000\tSID\tx\n",
     "not a Netscape cookie file"),
    # yt-dlp's loader asserts the include-subdomains flag matches a leading dot
    # on the domain, and refuses the WHOLE file when it does not — so a jar
    # with either of these must never be written.
    (".youtube.com\tFALSE\t/\tTRUE\t1893456000\tSID\tx\n",
     "not a Netscape cookie file"),
    ("youtube.com\tTRUE\t/\tTRUE\t1893456000\tSID\tx\n",
     "not a Netscape cookie file"),
    # Its loader also validates the expiry column (`[0-9]+(\.[0-9]+)?`).
    (".youtube.com\tTRUE\t/\tTRUE\tsometime\tSID\tx\n",
     "not a Netscape cookie file"),
]


def _capture_argv(fn, stdout):
    """The argv *fn* hands to the vendored yt-dlp, with run_tool stubbed.

    The binary path is exercised without starting a process: the stub records
    the command line and answers with the JSON a real run would print.
    `_load_ytdlp` is forced to None for the duration, because that is what
    decides WHICH path a machine takes — a machine with the module installed
    (this one included) would otherwise never reach the binary.
    """
    calls = []

    class _Proc:
        returncode = 0
        stderr = ""

    def fake_run(cmd, **kwargs):
        calls.append(list(cmd))
        proc = _Proc()
        proc.stdout = stdout
        return proc

    real_run, real_exe = youtube.run_tool, youtube._binary_exe
    real_mod = youtube._load_ytdlp
    youtube.run_tool = fake_run
    youtube._binary_exe = lambda: __file__  # any existing file will do
    youtube._load_ytdlp = lambda: None
    try:
        fn()
    finally:
        youtube.run_tool, youtube._binary_exe = real_run, real_exe
        youtube._load_ytdlp = real_mod
    assert calls, "the binary path never called run_tool"
    return calls[0]


class _FakeYDL:
    """Stands in for yt_dlp.YoutubeDL: records the options it was built with."""
    seen = []

    def __init__(self, opts):
        self.opts = opts
        _FakeYDL.seen.append(opts)

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        return False

    def extract_info(self, url, download=False):
        return {"entries": []}


class _FakeModule:
    YoutubeDL = _FakeYDL


def api_opts(config, outtmpl=None):
    """The dict the Python API path hands to YoutubeDL, captured for real."""
    _FakeYDL.seen = []
    real = youtube._load_ytdlp
    youtube._load_ytdlp = lambda: _FakeModule
    try:
        youtube._search("Radiohead - Creep", config)
    finally:
        youtube._load_ytdlp = real
    assert _FakeYDL.seen, "the Python path never built a YoutubeDL"
    return _FakeYDL.seen[-1]


try:
    # ----------------------------------------------------------------- #
    # 1. The validator
    # ----------------------------------------------------------------- #
    cookies, error = api_youtube.parse_cookie_file(REAL_JAR)
    assert error is None, f"a real Netscape file was refused: {error}"
    assert cookies == [("youtube.com", "LOGIN_INFO"),
                       ("youtube.com", "__Secure-3PSID"),
                       ("youtube.com", "SID"),
                       ("google.com", "NID")], cookies

    cookies, error = api_youtube.parse_cookie_file(SHAPED_ONLY)
    assert error is None, f"a headerless but well-shaped jar was refused: {error}"
    assert cookies == [("youtube.com", "SID")], cookies

    # A header with no cookie lines is still a cookie file (a signed-out
    # profile exports one) — it is accepted, and the warnings say it holds
    # nothing. Refusing it would only make the user re-export to be told the
    # same thing.
    cookies, error = api_youtube.parse_cookie_file(
        "# Netscape HTTP Cookie File\n# a signed-out profile\n")
    assert error is None and cookies == [], (cookies, error)
    assert api_youtube.cookie_warnings(cookies), \
        "an empty jar was saved with nothing said about it"

    for text, want in JUNK:
        cookies, error = api_youtube.parse_cookie_file(text)
        assert error and want in error, f"junk accepted: {text!r} -> {error!r}"
        assert not cookies, f"junk yielded cookies: {text!r}"

    # The warnings name what a real jar holds, so the user can tell a
    # signed-in export from a signed-out one without decoding the file.
    warnings = api_youtube.cookie_warnings(
        api_youtube.parse_cookie_file(REAL_JAR)[0])
    assert warnings and "youtube.com" in warnings[0], warnings
    only_google = api_youtube.cookie_warnings([("google.com", "NID")])
    assert "no youtube.com cookie" in only_google[0], only_google

    # ----------------------------------------------------------------- #
    # 2. `none` mode: no cookie option on either path
    # ----------------------------------------------------------------- #
    none_cfg = {"youtube_cookies_mode": "none"}
    assert youtube.cookie_opts(none_cfg) == {}, "none mode built an API option"
    assert youtube.cookie_args(none_cfg) == [], "none mode built a flag"
    opts = youtube._ydl_opts(none_cfg)
    assert "cookiefile" not in opts and "cookiesfrombrowser" not in opts, opts
    assert api_opts(none_cfg).get("cookiefile") is None, \
        "none mode reached YoutubeDL with a cookie option"

    # A mode the config validator would never let through is treated as none
    # rather than passed to yt-dlp as-is.
    assert youtube.cookie_args({"youtube_cookies_mode": "nonsense"}) == []

    # ----------------------------------------------------------------- #
    # 3. file mode, both paths
    # ----------------------------------------------------------------- #
    file_cfg = {"youtube_cookies_mode": "file"}
    # With no jar saved yet, file mode passes nothing: a `cookiefile` pointing
    # at a missing file would make every download fail with yt-dlp's own
    # "does not exist" instead of just running without cookies.
    assert not os.path.exists(JAR)
    assert youtube.cookie_opts(file_cfg) == {}, "file mode without a jar"
    assert youtube.cookie_args(file_cfg) == [], "file mode without a jar"

    api_youtube.write_cookie_file(REAL_JAR)
    assert os.path.isfile(JAR), JAR
    assert open(JAR, encoding="utf-8").read() == REAL_JAR

    assert youtube.cookies_path() == JAR, youtube.cookies_path()
    assert youtube.cookie_opts(file_cfg) == {"cookiefile": JAR}
    assert youtube.cookie_args(file_cfg) == ["--cookies", JAR]
    assert youtube._ydl_opts(file_cfg)["cookiefile"] == JAR
    assert api_opts(file_cfg)["cookiefile"] == JAR, \
        "the Python path built a YoutubeDL without the jar"

    # The download command line: `--cookies <jar>` immediately before the URL.
    argv = _capture_argv(
        lambda: youtube._download_binary(URL, os.path.join(tmp, "%(id)s.%(ext)s"),
                                         file_cfg),
        json.dumps({"id": "jNQXAC9IVRw", "title": "Me at the zoo"}))
    assert "--cookies" in argv, argv
    assert argv[argv.index("--cookies") + 1] == JAR, argv
    assert "--cookies-from-browser" not in argv, argv
    # The pinned exe is still the one being driven, and the flags around the
    # cookie option are untouched.
    assert argv[0] == __file__ and "-f" in argv and URL == argv[-1], argv

    # The search and probe calls the same binary makes carry it too.
    search_argv = _capture_argv(
        lambda: youtube._search("Radiohead - Creep", file_cfg),
        json.dumps({"entries": [{"id": "jNQXAC9IVRw", "title": "Creep"}]}))
    assert search_argv[search_argv.index("--cookies") + 1] == JAR, search_argv
    probe_argv = _capture_argv(
        lambda: youtube._probe_formats(URL, file_cfg),
        json.dumps({"id": "jNQXAC9IVRw", "requested_formats": [
            {"height": 720, "acodec": "none"},
            {"acodec": "opus", "abr": 128}]}))
    assert probe_argv[probe_argv.index("--cookies") + 1] == JAR, probe_argv

    # ----------------------------------------------------------------- #
    # 4. browser mode, both paths
    # ----------------------------------------------------------------- #
    browser_cfg = {"youtube_cookies_mode": "browser",
                   "youtube_cookies_browser": "firefox"}
    assert youtube.cookie_opts(browser_cfg) == {
        "cookiesfrombrowser": ("firefox",)}
    assert youtube.cookie_args(browser_cfg) == [
        "--cookies-from-browser", "firefox"]
    assert youtube._ydl_opts(browser_cfg)["cookiesfrombrowser"] == ("firefox",)
    assert api_opts(browser_cfg)["cookiesfrombrowser"] == ("firefox",)

    argv = _capture_argv(
        lambda: youtube._download_binary(URL, os.path.join(tmp, "%(id)s.%(ext)s"),
                                         browser_cfg),
        json.dumps({"id": "jNQXAC9IVRw"}))
    assert argv[argv.index("--cookies-from-browser") + 1] == "firefox", argv
    assert "--cookies" not in argv, argv

    # A browser yt-dlp does not know is never passed through: the setting
    # falls back to the default rather than making every download fail.
    assert youtube.cookie_args(
        {"youtube_cookies_mode": "browser",
         "youtube_cookies_browser": "netscape"}) == [
        "--cookies-from-browser", "chrome"]

    # ----------------------------------------------------------------- #
    # 5. The endpoints round-trip
    # ----------------------------------------------------------------- #
    state = api_youtube.youtube_cookies_get()
    assert state["present"] is True and state["mode"] == "none", state
    assert state["path"].replace("\\", "/") == JAR.replace("\\", "/"), state
    assert state["lines"] == 4, state
    assert state["sites"] == ["google.com", "youtube.com"], state
    assert state["bytes"] == len(REAL_JAR), state
    assert state["saved_at"] and state["saved_at"].endswith("+00:00"), state
    assert state["browsers"] == list(youtube.COOKIES_BROWSERS), state
    assert state["max_bytes"] == 512 * 1024, state

    saved = api_youtube.youtube_cookies_post(
        api_youtube.CookieUpload(text=REAL_JAR))
    assert saved["present"] and saved["lines"] == 4, saved
    assert saved["warnings"], "a save reported nothing about what it holds"
    assert open(JAR, encoding="utf-8").read() == REAL_JAR

    # Junk is refused with the reason, and the jar already on disk is left
    # exactly as it was: a refused paste must not half-replace a good jar.
    try:
        api_youtube.youtube_cookies_post(
            api_youtube.CookieUpload(text="not a cookie file at all"))
    except HTTPException as e:
        assert e.status_code == 400, e.status_code
        assert "Netscape" in e.detail, e.detail
    else:
        raise AssertionError("junk was accepted by the endpoint")
    assert open(JAR, encoding="utf-8").read() == REAL_JAR

    # The body ceiling is refused BY SIZE, before parsing: an oversize body
    # says how big it was and what the limit is.
    oversize = "x" * (api_youtube.MAX_COOKIE_BYTES + 1)
    try:
        api_youtube.youtube_cookies_post(api_youtube.CookieUpload(text=oversize))
    except HTTPException as e:
        assert e.status_code == 413, e.status_code
        assert "512 KiB" in e.detail, e.detail
    else:
        raise AssertionError("an oversize body was accepted")
    assert open(JAR, encoding="utf-8").read() == REAL_JAR

    deleted = api_youtube.youtube_cookies_delete()
    assert deleted["present"] is False, deleted
    assert not os.path.exists(JAR), JAR
    assert deleted["lines"] == 0 and deleted["sites"] == [], deleted
    # Deleting twice is not an error: the state is simply "absent".
    assert api_youtube.youtube_cookies_delete()["present"] is False

    # A headerless export is accepted (the shape is proof enough) and SAVED
    # with the magic header on line 1: http.cookiejar reads the first line as
    # the file's magic and refuses the whole jar when it is a cookie line, so
    # storing the paste verbatim would hand yt-dlp a jar it cannot read.
    saved = api_youtube.youtube_cookies_post(
        api_youtube.CookieUpload(text=SHAPED_ONLY))
    assert saved["lines"] == 1, saved
    on_disk = open(JAR, encoding="utf-8").read()
    assert on_disk.splitlines()[0] == api_youtube.NETSCAPE_HEADER, on_disk
    assert on_disk.endswith(SHAPED_ONLY), on_disk

    # The same jar through yt-dlp's OWN loader — the check that matters, since
    # the loader is what reads it on every download. Skipped (not failed) when
    # yt_dlp is not installed: the app supports that machine, and the option
    # plumbing above is already proven without it.
    try:
        from yt_dlp.cookies import YoutubeDLCookieJar
    except ImportError:
        print("note: yt_dlp is not importable here — its own loader check skipped")
    else:
        jar = YoutubeDLCookieJar(JAR)
        jar.load()
        # The domain keeps its leading dot: that IS the "any subdomain of
        # youtube.com" form cookiejar stores, which is what makes the cookie
        # travel to every youtube.com request.
        loaded = sorted((c.name, c.domain) for c in jar)
        assert loaded == [("SID", ".youtube.com")], loaded
        print(f"note: yt-dlp's own loader read {len(jar)} cookie(s) from the saved jar")
    api_youtube.youtube_cookies_delete()

    # ----------------------------------------------------------------- #
    # 6. The settings themselves
    # ----------------------------------------------------------------- #
    assert cfgmod.DEFAULT_CONFIG["youtube_cookies_mode"] == "none"
    assert cfgmod.DEFAULT_CONFIG["youtube_cookies_browser"] == "chrome"
    # The validator takes any case and falls back to the default for anything
    # it does not know, exactly like every other choice key.
    cfg = cfgmod.normalize_config({"youtube_cookies_mode": "Browser",
                                   "youtube_cookies_browser": "Edge"})
    assert cfg["youtube_cookies_mode"] == "browser", cfg["youtube_cookies_mode"]
    assert cfg["youtube_cookies_browser"] == "edge", cfg["youtube_cookies_browser"]
    cfg = cfgmod.normalize_config({"youtube_cookies_mode": "wat",
                                   "youtube_cookies_browser": "lynx"})
    assert cfg["youtube_cookies_mode"] == "none", cfg["youtube_cookies_mode"]
    assert cfg["youtube_cookies_browser"] == "chrome", cfg["youtube_cookies_browser"]

    print("PASS  yt-dlp cookie jar: validation, both paths, endpoints, settings")
finally:
    if OUT:
        os.environ["MLO_MUSIC_FOLDER"] = OUT
    else:
        os.environ.pop("MLO_MUSIC_FOLDER", None)
    for _mod, _path in _real_config_files.items():
        _mod.CONFIG_FILE = _path
    cfgmod._MIGRATED = False
    shutil.rmtree(tmp, ignore_errors=True)
