#!/usr/bin/env python3
"""The RateYourMusic credential: import the RYM cookies out of a cookies.txt.

Every claim below is about the real code, not a copy of it:

  * a browser extension's export (the whole profile, signed in to RYM) is
    filtered down to its rateyourmusic.com cookies — the YouTube and Google
    cookies in the same file must NOT land in `rym_cookie`, a lookalike domain
    (`rateyourmusic.com.example.net`) must not either, and a subdomain of RYM's
    own must;
  * the survivors are written into `rym_cookie` in FILE ORDER, as the
    `name=value; name=value` header a user could have typed into the settings
    box — and the value is really persisted, not just held in the process;
  * the scraper reads it back: `integrations._rym_cookie` returns the stored
    header verbatim and `integrations._rym_cookiejar` hands out the `session`
    cookie — so an import reaches the request RYM is actually asked with;
  * the HttpOnly `session` cookie survives the import (the reason this route
    exists) and is reported as such; a jar with RYM cookies but no `session`
    is stored AND warned about;
  * a well-formed export with no rateyourmusic.com cookie in it stores
    NOTHING and says why — the credential that was working is left exactly as
    it was; junk and an empty paste are refused with the parser's own
    sentence, and an oversize body by size, all three before any write;
  * nothing this module answers with ever contains a cookie VALUE: no route
    returns it, so no state a client can hold can leak it;
  * the shared Netscape parser (`server/cookies.py`) still
    answers the yt-dlp jar with names only unless values are asked for.

Hermetic: the music folder is redirected to a temp dir (MLO_MUSIC_FOLDER) and
mlo.config/mlo.paths' CONFIG_FILE to a temp stub, so the config under test is
<tmp>/Music/.mlo/data/config.json and the real install's config.json is never
read or written. No network is used.

Run:  python tools/test_rym_cookies.py
"""
import json
import os
import shutil
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

OUT = os.environ.pop("MLO_MUSIC_FOLDER", None)  # keep the test hermetic

tmp = tempfile.mkdtemp(prefix="mlo_rymcookies_")
music = os.path.join(tmp, "Music")
os.makedirs(music)
os.environ["MLO_MUSIC_FOLDER"] = music

import mlo.config as cfgmod  # noqa: E402

stub_config = os.path.join(tmp, "config.json")
_real_config_files = {mod: mod.CONFIG_FILE for mod in (cfgmod,)}
for _mod in (cfgmod,):
    _mod.CONFIG_FILE = stub_config

from fastapi import HTTPException  # noqa: E402

from server import api_rym, cookies as cookie_mod, integrations  # noqa: E402

# What a browser extension writes for a profile signed in to rateyourmusic.com:
# the header, comment lines, and one line per cookie for EVERY site the profile
# holds — the RYM session is `#HttpOnly_` (which is why this import exists at
# all: the extension is the only way a user can hand that cookie over), and the
# last line is a lookalike domain someone else owns.
REAL_JAR = (
    "# Netscape HTTP Cookie File\n"
    "https://curl.se/docs/http-cookies.html\n"
    "# This file was generated by a browser extension.  Do not edit.\n"
    "\n"
    "#HttpOnly_.rateyourmusic.com\tTRUE\t/\tTRUE\t1893456000\tsession\tS3SSION-VALUE\n"
    ".rateyourmusic.com\tTRUE\t/\tTRUE\t1893456000\tcf_clearance\tCF-VALUE\n"
    "rateyourmusic.com\tFALSE\t/\tTRUE\t1893456000\tcsrf_token\tCSRF-VALUE\n"
    ".youtube.com\tTRUE\t/\tTRUE\t1893456000\tSID\tYT-VALUE\n"
    ".google.com\tTRUE\t/\tFALSE\t1893456000\tNID\t523=abc\n"
    ".rateyourmusic.com.example.net\tTRUE\t/\tTRUE\t1893456000\tnot_ours\tNOPE-VALUE\n"
)

# The RYM pairs of the file above, in file order — the exact value `rym_cookie`
# must hold afterwards.
STORED = "session=S3SSION-VALUE; cf_clearance=CF-VALUE; csrf_token=CSRF-VALUE"

# A jar from a profile signed in to YouTube only: it parses, and it holds
# nothing this credential can use.
OTHER_JAR = (
    "# Netscape HTTP Cookie File\n"
    ".youtube.com\tTRUE\t/\tTRUE\t1893456000\tSID\tYT-ONLY\n"
    ".google.com\tTRUE\t/\tFALSE\t1893456000\tNID\t523=abc\n"
)

# A signed-out profile's export: the header, no cookie lines at all.
EMPTY_JAR = "# Netscape HTTP Cookie File\n# a signed-out profile\n"

# The same shape with no header line: the extension's own header is optional
# proof (7 tab-separated columns is the other one).
SHAPED_ONLY = "rateyourmusic.com\tFALSE\t/\tTRUE\t1893456000\tsession\tSHAPED\n"

SUBDOMAIN_JAR = (
    "# Netscape HTTP Cookie File\n"
    ".music.rateyourmusic.com\tTRUE\t/\tTRUE\t1893456000\tsubcookie\tSUB-VALUE\n"
)

NO_SESSION_JAR = (
    "# Netscape HTTP Cookie File\n"
    ".rateyourmusic.com\tTRUE\t/\tTRUE\t1893456000\tcf_clearance\tCF2-VALUE\n"
)

JUNK = [
    ("just some words\nand more words\n", "not a Netscape cookie file"),
    ('{"cookies": [{"name": "session"}]}\n', "not a Netscape cookie file"),
    # 7 columns, but the flags are not booleans — the shared parser's own rule
    # (yt-dlp's loader refuses the WHOLE file when they are broken).
    (".rateyourmusic.com\tMAYBE\t/\tTRUE\t1893456000\tsession\tx\n",
     "not a Netscape cookie file"),
    # A leading dot and a FALSE flag disagree: the shared parser rejects it,
    # so a jar yt-dlp would refuse can never become this credential either.
    (".rateyourmusic.com\tFALSE\t/\tTRUE\t1893456000\tsession\tx\n",
     "not a Netscape cookie file"),
]

# Every secret the fixtures carry: none of them may appear in an API answer.
SECRETS = ["S3SSION-VALUE", "CF-VALUE", "CSRF-VALUE", "YT-VALUE", "YT-ONLY",
           "NOPE-VALUE", "SHAPED", "SUB-VALUE", "CF2-VALUE", "MANUAL-VALUE"]


def stored():
    """The `rym_cookie` value the app would use on its next request."""
    return cfgmod.load_config()["rym_cookie"]


def assert_no_values(payload, where):
    """The response is names, counts and sentences — never a cookie value."""
    blob = json.dumps(payload)
    for secret in SECRETS:
        assert secret not in blob, f"{where} leaked a cookie value: {blob}"


def post(text):
    return api_rym.rym_cookies_post(api_rym.CookieUpload(text=text))


def refused(text, want):
    """The 400 this text is refused with, with *want* in the sentence."""
    try:
        post(text)
    except HTTPException as e:
        assert e.status_code == 400, e.status_code
        assert want in e.detail, e.detail
        return e.detail
    raise AssertionError(f"accepted: {text!r}")


try:
    # ----------------------------------------------------------------- #
    # 1. The parse: one parser, no fork
    # ----------------------------------------------------------------- #
    plain, error = cookie_mod.parse_cookie_file(REAL_JAR)
    assert error is None, error
    assert plain == [("rateyourmusic.com", "session"),
                     ("rateyourmusic.com", "cf_clearance"),
                     ("rateyourmusic.com", "csrf_token"),
                     ("youtube.com", "SID"),
                     ("google.com", "NID"),
                     ("rateyourmusic.com.example.net", "not_ours")], plain

    with_values, error = cookie_mod.parse_cookie_file(REAL_JAR, with_values=True)
    assert error is None, error
    assert with_values[0] == ("rateyourmusic.com", "session", "S3SSION-VALUE"), \
        with_values[0]
    # The yt-dlp jar's own answer is unchanged: names and domains only.
    assert all(len(row) == 2 for row in plain), plain

    # The filter: RYM's own host and its subdomains, nothing else.
    pairs = api_rym.rym_pairs(with_values)
    assert pairs == [("session", "S3SSION-VALUE"), ("cf_clearance", "CF-VALUE"),
                     ("csrf_token", "CSRF-VALUE")], pairs

    # ----------------------------------------------------------------- #
    # 2. The import: the RYM cookies, in file order, persisted
    # ----------------------------------------------------------------- #
    saved = post(REAL_JAR)
    assert saved["stored"] == 3, saved
    assert saved["present"] is True and saved["lines"] == 3, saved
    assert saved["names"] == ["session", "cf_clearance", "csrf_token"], saved
    assert saved["session"] is True, saved
    assert saved["sites"] == ["rateyourmusic.com"], saved
    assert saved["warnings"] == [], saved  # a session cookie is worth nothing to warn about
    assert_no_values(saved, "the import's answer")

    assert stored() == STORED, stored()
    # The YouTube/Google cookies in the same file stayed out, and so did the
    # lookalike domain's.
    assert "SID" not in stored() and "NID" not in stored(), stored()
    # Persisted, not just held in the process the import ran in.
    with open(cfgmod.active_config_file(), encoding="utf-8") as fh:
        assert json.load(fh)["rym_cookie"] == STORED, "the import was not written"

    # ----------------------------------------------------------------- #
    # 3. GET describes the STORED value, and the scraper reads it back
    # ----------------------------------------------------------------- #
    state = api_rym.rym_cookies_get()
    assert state["present"] is True and state["lines"] == 3, state
    assert state["names"] == saved["names"], state
    assert state["sites"] == ["rateyourmusic.com"], state
    assert state["max_bytes"] == 512 * 1024, state
    assert_no_values(state, "GET")

    # The live credential the RYM requests are made with: the same value the
    # manual box would have held, normalised by the scraper's own reader.
    assert integrations._rym_cookie() == STORED, integrations._rym_cookie()
    jar = integrations._rym_cookiejar()
    assert jar.get("session", domain="rateyourmusic.com") == "S3SSION-VALUE", jar

    # ----------------------------------------------------------------- #
    # 4. Warnings: no `session`, and nothing stored at all
    # ----------------------------------------------------------------- #
    saved = post(NO_SESSION_JAR)
    assert saved["stored"] == 1 and saved["session"] is False, saved
    assert saved["names"] == ["cf_clearance"], saved
    assert saved["warnings"] and "session" in saved["warnings"][0], saved
    assert_no_values(saved, "the no-session import")
    assert stored() == "cf_clearance=CF2-VALUE", stored()
    # `session` is HttpOnly: the panel must say a guest RYM is what answers.
    assert "guest" in api_rym.rym_cookies_get()["warnings"][0], \
        api_rym.rym_cookies_get()["warnings"]

    # A subdomain of RYM's own host is RYM's cookie.
    saved = post(SUBDOMAIN_JAR)
    assert saved["stored"] == 1 and stored() == "subcookie=SUB-VALUE", saved

    # ----------------------------------------------------------------- #
    # 5. Nothing stored from a jar that holds no RYM cookie
    # ----------------------------------------------------------------- #
    before = stored()
    assert before, "the previous credential must be worth protecting"
    saved = post(OTHER_JAR)
    assert saved["stored"] == 0, saved
    assert saved["names"] == ["subcookie"], saved  # the OLD credential is untouched
    assert saved["warnings"], "a file with no RYM cookie said nothing"
    assert "rateyourmusic.com" in saved["warnings"][0], saved["warnings"]
    assert_no_values(saved, "the no-RYM-jar import")
    assert stored() == before, stored()

    # The same for a signed-out profile's export (a header, no cookie lines):
    # the shared parser accepts it, and it replaces nothing.
    saved = post(EMPTY_JAR)
    assert saved["stored"] == 0 and saved["names"] == ["subcookie"], saved
    assert saved["warnings"], saved
    assert stored() == before, stored()

    # ----------------------------------------------------------------- #
    # 6. Junk, an empty paste and an oversize body: refused before any write
    # ----------------------------------------------------------------- #
    junk_detail = refused("", "the file is empty")
    assert "rateyourmusic.com" in junk_detail, junk_detail
    for text, want in JUNK:
        refused(text, want)
    assert stored() == before, stored()

    oversize = "# Netscape HTTP Cookie File\n" + \
        ".rateyourmusic.com\tTRUE\t/\tTRUE\t1893456000\tsession\t" + "x" * 600000 + "\n"
    try:
        post(oversize)
    except HTTPException as e:
        assert e.status_code == 413, e.status_code
        assert "1024 KiB" in e.detail or "KiB" in e.detail, e.detail
    else:
        raise AssertionError("an oversize body was accepted")
    assert stored() == before, stored()

    # ----------------------------------------------------------------- #
    # 7. A headerless export is still a cookie file
    # ----------------------------------------------------------------- #
    saved = post(SHAPED_ONLY)
    assert saved["stored"] == 1 and saved["session"] is True, saved
    assert stored() == "session=SHAPED", stored()

    # ----------------------------------------------------------------- #
    # 8. The manual box and the import agree
    # ----------------------------------------------------------------- #
    cfg = cfgmod.load_config()
    cfg["rym_cookie"] = "Cookie: session=MANUAL-VALUE; cf_clearance=M2"
    assert cfgmod.save_config(cfg), "could not write the config"
    state = api_rym.rym_cookies_get()
    assert state["names"] == ["session", "cf_clearance"], state
    assert state["warnings"] == [], state
    assert_no_values(state, "GET over a hand-pasted header")
    assert integrations._rym_cookie() == "session=MANUAL-VALUE; cf_clearance=M2", \
        integrations._rym_cookie()

    # Clearing it (the panel's own action goes through /api/config, so an
    # empty value is the whole "remove the credential" story).
    cfg = cfgmod.load_config()
    cfg["rym_cookie"] = ""
    assert cfgmod.save_config(cfg)
    state = api_rym.rym_cookies_get()
    assert state == {"present": False, "lines": 0, "sites": [], "names": [],
                     "max_bytes": 512 * 1024,
                     "warnings": ["no RateYourMusic cookie saved — "
                                  "rateyourmusic.com is asked as a guest, so a "
                                  "release it will not serve is read from the "
                                  "archived copy instead"]}, state

    print("PASS  RateYourMusic cookie import: filter, config write, warnings, "
          "endpoints (no value ever returned)")
finally:
    if OUT:
        os.environ["MLO_MUSIC_FOLDER"] = OUT
    else:
        os.environ.pop("MLO_MUSIC_FOLDER", None)
    for _mod, _path in _real_config_files.items():
        _mod.CONFIG_FILE = _path
    cfgmod._MIGRATED = False
    shutil.rmtree(tmp, ignore_errors=True)
